openapi: 3.0.2
info:
  contact:
    email: adrian.nuta@manticoresearch.com
  description: |
    This is the API for Manticore Search HTTP protocol
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Manticore Search API
  version: 1.0.0
externalDocs:
  description: Find out more about Manticore Search
  url: https://manticoresearch.com/
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/adriannuta/ManticoreSeach/1.0.0
tags:
- description: Operations regarding adding, updating or deleting documents
  name: Index
- description: Operations about performing searches over indexes
  name: Search
paths:
  /json/search:
    post:
      externalDocs:
        url: https://docs.manticoresearch.com/latest/html/http_reference/json_insert.html
      operationId: search
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/searchRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/searchResponse'
          description: Ok
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
          description: error
      summary: Performs a search
      tags:
      - Search
  /json/insert:
    post:
      externalDocs:
        url: https://docs.manticoresearch.com/latest/html/http_reference/json_insert.html
      operationId: insert
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/insertDocumentRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successResponse'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
          description: error
      summary: Create a new document in an index
      tags:
      - Index
  /json/replace:
    post:
      externalDocs:
        url: https://docs.manticoresearch.com/latest/html/http_reference/json_insert.html
      operationId: replace
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/insertDocumentRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successResponse'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
          description: error
      summary: Replace new document in an index
      tags:
      - Index
  /json/update:
    post:
      externalDocs:
        url: https://docs.manticoresearch.com/latest/html/http_reference/json_update.html
      operationId: update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateDocumentRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successResponse'
          description: item updated
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
          description: error
      summary: Update a document in an index
      tags:
      - Index
  /json/delete:
    post:
      externalDocs:
        url: https://docs.manticoresearch.com/latest/html/http_reference/json_update.html
      operationId: delete
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deleteDocumentRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successResponse'
          description: item updated
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
          description: error
      summary: Delete a document in an index
      tags:
      - Index
components:
  schemas:
    searchRequest:
      properties:
        index:
          type: string
        query:
          type: object
        limit:
          minimum: 0
          type: integer
        offset:
          minimum: 0
          type: integer
        max_matches:
          minimum: 0
          type: integer
        sort:
          items:
            oneOf:
            - type: string
            - type: object
          type: array
        script_fields:
          type: object
        highlight:
          type: object
        _source:
          oneOf:
          - type: string
          - type: object
        profile:
          type: boolean
      required:
      - index
      - query
      type: object
    updateDocumentRequest:
      example:
        index: test
        doc:
          price: 1000
        query:
          match:
            '*': apple
      properties:
        index:
          type: string
        doc:
          type: object
        id:
          format: int64
          minimum: 1
          type: integer
        query:
          type: object
      required:
      - doc
      - index
      type: object
    deleteDocumentRequest:
      example:
        index: test
        id: 1
      properties:
        index:
          type: string
        id:
          format: int64
          minimum: 1
          type: integer
        doc:
          type: object
      required:
      - index
      type: object
    insertDocumentRequest:
      example:
        title: This is some title
        gid: 100
      properties:
        index:
          type: string
        id:
          format: int64
          minimum: 1
          type: integer
        doc:
          type: object
      required:
      - doc
      - index
      type: object
    searchResponse:
      example:
        hits:
          hits:
          - '{}'
          - '{}'
          total: 6
        took: 0
        profile: '{}'
        timed_out: true
      properties:
        took:
          type: integer
        timed_out:
          type: boolean
        hits:
          $ref: '#/components/schemas/searchResponse_hits'
        profile:
          type: object
      type: object
    successResponse:
      example:
        result: result
        found: true
        _index: _index
        created: true
        _id: 0
      properties:
        _index:
          type: string
        _id:
          format: int64
          type: integer
        created:
          type: boolean
        result:
          type: string
        found:
          type: boolean
      required:
      - _id
      - _index
      - result
      type: object
    errorResponse:
      properties:
        error:
          type: object
        status:
          example: 500
          type: integer
      required:
      - error
      - status
      type: object
    searchResponse_hits:
      example:
        hits:
        - '{}'
        - '{}'
        total: 6
      properties:
        total:
          type: integer
        hits:
          items:
            type: object
          type: array
