openapi: 3.0.2

info:
  title: Manticore Search API
  description: | 
    This is the API for Manticore Search HTTP protocol
  version: "1.0.0"
  contact:
    name: Manticore Software Ltd.
    email: info@manticoresearch.com
    url: https://manticoresearch.com/contact-us/
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Index
    description: Operations regarding adding, updating or deleting documents
  - name: Search
    description: Operations about performing searches over indexes
  - name: Utils
    description: Various operations 
externalDocs:
  description: Find out more about Manticore Search
  url: 'https://manticoresearch.com/'    
components:
  schemas:
    searchRequest:
      type: object
      description: Payload for search operation
      required:
        - index
        - query
      properties:
        index:
          type: string
        query:
          type: object
        limit:
          type: integer
          minimum: 0
        offset:
          type: integer
          minimum: 0
        max_matches:
          type: integer
          minimum: 0
        sort:
          type: array
          items:
            oneOf:
              - type: string
              - type: object
        script_fields:
          type: object
        highlight:
          type: object
        _source:
          oneOf:
            - type: string
            - type: object
        profile:
          type: boolean
    updateDocumentRequest:
      type: object
      description: Payload for update document
      required:
        - index
        - doc
      properties:
        index:
          type: string
        doc:
          type: object
        id:  
          type: integer
          format: int64          
          minimum: 1
        query:  
          type: object
      example:
        index: test
        doc: 
          price: 1000
        query:
          match:
             '*': apple          
    deleteDocumentRequest:
      type: object
      description: | 
        Payload for delete request.
        Documents can be deleted either one by one by specifying the document id
        or by providing a query object.
        For more information see 
        [Delete API](https://docs.manticoresearch.com/latest/html/http_reference/json_delete.html)
      required:
        - index
      properties:
        index:
          type: string
        id:  
          type: integer
          format: int64          
          minimum: 1
        query:
          type: object
      example:
        index: test
        id: 1    
    bulkRequest:
      type: object
      description: list of operations
    insertDocumentRequest:
      type: object
      description: |
        Object with document data.
      required:
        - index
        - doc
      properties:
        index:
         type: string
         description: Name of the index
        id:  
          type: integer
          format: int64          
          minimum: 1
          description: | 
            Document ID.
        doc:
          type: object
          description: |
            Object with document data
      example:
        title: "This is some title"
        gid: 100    
    percolateRequest:
      type: object
      description: Object with documents to percolate
      required: 
        - query
      properties:
        query:
          type: object
          required: 
            - percolate
          properties:
            percolate:
              type: object
    searchResponse:
      type: object
      description: Response object of a search request
      properties:
        took:
          type: integer
        timed_out:
          type: boolean
        hits:
          type: object
          properties:
            total:
              type: integer
            hits:
              type: array
              items:
                type: object
        profile:
          type: object
          
    sqlResponse:
      type: object
      description: Response from sql depends on the query executed.
    successResponse:
      type: object
      description: Success response
      required:
        - _index
        - _id
        - result
      properties:
        _index:
          type: string
        _id:
          type: integer
          format: int64
        created:
          type: boolean
        result:
          type: string
        found:
          type: boolean
    errorResponse:
      type: object
      description: Error response
      required:
        - error
        - status
      properties:
        error:
          type: object
        status:
          type: integer
          example: 500

        
paths:
  /json/search:
    post:
      summary: Performs a search
      operationId: search
      tags:
        - Search
      externalDocs:
        url: https://docs.manticoresearch.com/latest/html/http_reference/json_insert.html
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/searchRequest'
      responses:
        '200':
          description: Ok
          content:
             application/json:
               schema: 
                  $ref: '#/components/schemas/searchResponse'
        default:
          description: error
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/errorResponse'
  /json/insert:
    post:
      summary: Create a new document in an index
      operationId: insert
      tags:
        - Index      
      externalDocs:
        url: https://docs.manticoresearch.com/latest/html/http_reference/json_insert.html
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/insertDocumentRequest'
      responses:
        '200':
          description: OK
          content:
             application/json:
               schema: 
                  $ref: '#/components/schemas/successResponse'
        default:
          description: error
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/errorResponse'
  /json/replace:
    post:
      summary: Replace new document in an index
      operationId: replace
      tags:
        - Index      
      externalDocs:
        url: https://docs.manticoresearch.com/latest/html/http_reference/json_insert.html
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/insertDocumentRequest'
      responses:
        '200':
          description: OK
          content:
             application/json:
               schema: 
                  $ref: '#/components/schemas/successResponse'
        default:
          description: error
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/errorResponse'                  
  /json/update:
    post:
      summary: Update a document in an index
      operationId: update
      tags:
        - Index      
      externalDocs:
        url: https://docs.manticoresearch.com/latest/html/http_reference/json_update.html
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateDocumentRequest'

      responses:
        '200':
          description: item updated
          content:
             application/json:
               schema: 
                  $ref: '#/components/schemas/successResponse'
        default:
          description: error
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/errorResponse'
  /json/delete:
    post:
      summary: Delete a document in an index
      operationId: delete
      tags:
        - Index      
      externalDocs:
        url: https://docs.manticoresearch.com/latest/html/http_reference/json_update.html
      requestBody:
        required: true
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/deleteDocumentRequest'

      responses:
        '200':
          description: item updated
          content:
             application/json:
               schema: 
                  $ref: '#/components/schemas/successResponse'
        default:
          description: error
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/errorResponse'        
  /json/bulk:
    post:
      summary: Bulk index operations
      operationId: bulk
      tags:
        - Index      
      externalDocs:
        url: https://docs.manticoresearch.com/latest/html/http_reference/json_update.html
      requestBody:
        required: true
        content:
          application/x-ndjson:
            schema:
             $ref: '#/components/schemas/bulkRequest'

      responses:
        '200':
          description: item updated
          content:
             application/json:
               schema: 
                  $ref: '#/components/schemas/successResponse'
        default:
          description: error
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/errorResponse'                          
  /json/pq/search:
    post:
      summary: Perform reverse search on a percolate index
      operationId: percolate
      tags:
        - Search      
      externalDocs:
        url: https://docs.manticoresearch.com/latest/html/http_reference/json_update.html
      requestBody:
        required: true
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/percolateRequest'

      responses:
        '200':
          description: items found
          content:
             application/json:
               schema: 
                  $ref: '#/components/schemas/searchResponse'
        default:
          description: error
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/errorResponse'                           
  /sql:
    post:
      summary: Perform SQL requests
      operationId: sql
      tags:
        - utils
      externalDocs:
        url: https://docs.manticoresearch.com/latest/html/httpapi_reference.html#sql-api
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
               schema: 
                  type: object
                  required:
                    - query
                  properties:
                    query:
                      type: string
                    mode:
                      type: string
      responses:
        '200':
          description: item updated
          content:
             application/json:
               schema: 
                  $ref: '#/components/schemas/sqlResponse'
        default:
          description: error
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/errorResponse'        
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/adriannuta/ManticoreSeach/1.0.0